version: 2
executorType: docker
containerInfo:
  - image: rh389/node-base
  - image: deangiberson/aws-dynamodb-local

jobs:
  build:
    workDir: ~/workspace
    steps:
      - type: checkout
      - restore_cache:
          key: v1-yarn
      - type: shell
        shell: /bin/sh
        command: yarn install && yarn test
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules

workflows:
  version: 2
  build:
    jobs:
      - build

